[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = [
  "cd backend",
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd backend && java -jar target/*.jar"
